version: '3'

# Named volumes
volumes:
  # MySQL Data
  mysql:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: mysql-petshop
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petshop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mudar123